image: i386/alpine:3.8

definitions:
  steps:
    - step: &compile
        name: Compile plugin
        artifacts:
          - smdir/addons/sourcemod/plugins/ProxyKiller.smx
        script:
          - apk update
          - apk add jq wget libc6-compat libstdc++
          - mkdir smdir
          - wget -q -O - "http://sourcemod.net/latest.php?os=linux&version=1.9" | tar x -C ./smdir -vzf -
          - eval PLUGIN_URL=$(cat pipelines-configuration.json | jq ".${_deployment}.PLUGIN_URL")
          - eval PLUGIN_VERSION=$(cat pipelines-configuration.json | jq ".${_deployment}.PLUGIN_VERSION")
          - eval PLUGIN_SPEWMODE=$(cat pipelines-configuration.json | jq ".${_deployment}.PLUGIN_SPEWMODE")
          - eval PLUGIN_SPEWLEVEL=$(cat pipelines-configuration.json | jq ".${_deployment}.PLUGIN_SPEWLEVEL")
          - echo -e "#define PROXYKILLER_URL \"${PLUGIN_URL}\"" >> ./include/ProxyKiller_Version.inc
          - echo -e "#define PROXYKILLER_VERSION \"${PLUGIN_VERSION}\"" >> ./include/ProxyKiller_Version.inc
          - echo -e "#define PROXYKILLER_SPEWMODE ${PLUGIN_SPEWMODE}" >> ./include/ProxyKiller_Version.inc
          - echo -e "#define PROXYKILLER_SPEWLEVEL ${PLUGIN_SPEWLEVEL}" >> ./include/ProxyKiller_Version.inc
          - for file in *.sp; do ./smdir/addons/sourcemod/scripting/spcomp $file -i ./include; done;
          - mv ./*.smx ./smdir/addons/sourcemod/plugins/

    - step: &build
        name: Build Release
        trigger: manual
        artifacts:
          - builds/*
        script:
          - apk update
          - mkdir builds
          - cp smdir/addons/sourcemod/plugins/ProxyKiller.smx builds/ProxyKiller-latest.smx
          - cp smdir/addons/sourcemod/plugins/ProxyKiller.smx builds/ProxyKiller-v${BITBUCKET_TAG}.smx

    - step: &deploy
        name: Deploy Release
        script:
          - apk update
          - apk add curl
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"builds/ProxyKiller-v${BITBUCKET_TAG}.smx"
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"builds/ProxyKiller-latest.smx"

pipelines:
  custom:
    compile:
      - step: 
          <<: *compile
          deployment: staging

  pull-requests:
    '*':
      - step: 
          <<: *compile
          deployment: staging

  tags:
    '*':
      - step: 
          <<: *compile
          deployment: production
      - step: *build
      - step: *deploy